### ISSUE TITLE
gm abbreviation for gram?!

### ISSUE THREAD

**Issue by Gitlish** [deefrawley/Flow.Launcher.Plugin.GenConvert#12]
The official SI abbreviation for gram is g. Every other metric abbreviation in this plugin uses its proper SI abbreviation. "g" isn't used as an abbreviation for any other unit in this plugin. Can this abbreviation please be changed to its only logical one – "g"? Thanks.

**Comment by deefrawley** [comment]
Makes sense - it should be the official abbreviation. I'll push out a small update soon to fix

**Comment by Gitlish** [comment]
Thank you!
