### ISSUE TITLE
Add imperial and metric ton units

### ISSUE THREAD

**Issue by Gitlish** [deefrawley/Flow.Launcher.Plugin.GenConvert#14]
G'day Damien,

First off – thanks for this plugin! It's very handy once you get used to the syntax.

For consistency and completeness, you may want to add imperial and metric ton units:

**Unit** / **Abbreviation**
US ton / ton
Imperial ton / tonimp
Metric ton / t
	
- "ton" is already there, but its unit name is ambiguous; I'd suggest changing from "ton" to "US ton". 1 US ton = 2,000 pounds.
- 1 Imperial ton = 2,240 pounds.
- "Metric ton" is otherwise known as "tonne", but former more descriptive – take your pick. Its metric abbreviation is "t", which is unused elsewhere in this plugin. 1 tonne = 1000 kg = 2,204.6226218488 pounds.

-jim.

**Comment by deefrawley** [comment]
G'day Jim,
Glad you're finding the plugin useful.
Yep can align this with the other metric/US/imperial measurements. I'll get an update out today.

**Comment by deefrawley** [comment]
Here's what I plan:

Metric tonne - abbrev "t", 0.000001 grams (base unit)
US (long) ton - abbrev "ust", 0.0000011023109950010196 grams (base unit)
UK (short) ton - abbrev "ukt", 0.00000098421 grams (base unit)

The official abbreivation for long and short tons are l.t and sh.t which I don't particularly like as no other abbreviations have full stops in them.
Does that make sense?

**Comment by Gitlish** [comment]
I'd stick with "US ton" and "Imperial ton" – no one calls them long or short, at least not in US or Australia and most of the world doesn't care, because they use metric). And US and Imperial are consistent with how you differentiate the other US/UK units. My suggestion:

- Metric ton" (or "tonne") – abbrev "t" ("Metric tonne" is redundant)
- "US ton" – abbrev "ton" (like you've done with cup, pint, tsp etc.: no "US" in abbreviation. And "ton" is the abbreviation you use now, so won't break anyone.)
- "Imperial ton" – abbrev "tonimp" ((like you've done with cup, pint, tsp etc.: "imp" suffix in abbreviation)

This is certainly US-centric, but that aligns with the other abbreviations you've used. When users have to remember the correct unit abbreviations to quickly use this plugin, consistency is key.
