### ISSUE TITLE
Only trigger plugin when number is entered

### ISSUE THREAD

**Issue by ThinkSalat** [deefrawley/Flow.Launcher.Plugin.GenConvert#17]
Hi,

I'd like to use this plugin with the wildcard action keyword, so I don't have to type in 'gc' or remember it. It would operate how the calculator operates: checks if the input is a number and only activate if so. 

I'm not sure if this can be done through the plugin itself or must be done through the flow app, but this is an annoyance because if you have it set to * the following happens for any input into the launcher:
 
![image](https://user-images.githubusercontent.com/31082405/218612998-e4e44807-e4ae-4f5f-8357-6a4364b07440.png)

There could also be added the option to not show any of those

**Comment by deefrawley** [comment]
Updated in v2.0.0
