### ISSUE TITLE
meters to miles appears not working here

### ISSUE THREAD

**Issue by rmontroni** [deefrawley/Flow.Launcher.Plugin.GenConvert#21]
![image](https://github.com/deefrawley/Flow.Launcher.Plugin.GenConvert/assets/116408463/fdd586e4-a6ee-49f0-a2b7-c2209ec85907)

**Comment by deefrawley** [comment]
That's odd. Have you got the latest plugin version as it works for me (type `pm update` and see if an update is listed)

![image](https://github.com/deefrawley/Flow.Launcher.Plugin.GenConvert/assets/18594055/1a156478-b05d-41a1-9689-cbc78f1dfa06)

**Comment by deefrawley** [comment]
@rmontroni does this issue persist?

**Comment by deefrawley** [comment]
Closing as inactive
