### ISSUE TITLE
list all available convertions

### ISSUE THREAD

**Issue by jjw24** [deefrawley/Flow.Launcher.Plugin.GenConvert#5]
can we add the listing of all available conversions with this plugin, i.e. i type the gc action keyword then a list of available conversions show up like the bookmarks plugin. Can also be a dedicated way of listing the conversions as well. 

List by subject should be sufficient I suppose.

**Comment by deefrawley** [comment]
Should be able to do something. Perhaps I'll add a query for the categories and list the units in each while just the keyword is entered and no arguments.

**Comment by jjw24** [comment]
Yeah, the reason for this is when I was wondering if the plugin had the conversion I wanted, I had to jump on the repo readme to figure out, just thought it might be easier from the plugin to get a list straight away.

**Comment by deefrawley** [comment]
@jjw24 v1.1 should improve this a lot along with several other enhancements. Open another ticket if you find any issues it.
