### ISSUE TITLE
Rounding of result

### ISSUE THREAD

**Issue by jjw24** [deefrawley/Flow.Launcher.Plugin.GenConvert#8]
Any chance the rounding can be without so many decimals?

![image](https://user-images.githubusercontent.com/26427004/147874846-522e250c-e346-49b9-9c15-e8aaa4f1ea9e.png)

**Comment by deefrawley** [comment]
Be _less_ precise? You're clearly not an engineer! 😛 
I'll have a look

**Comment by deefrawley** [comment]
@jjw24 - cleaned up the precision with this new build.
